import { CheckCircle2, Leaf, ScanSearch } from 'lucide-react'

function LeafDetectionResultPanel({ result }) {
  const detected = Boolean(result?.detected)
  const confidence = Number(result?.confidence || 0)
  return <section className="dashboard-card rounded-[12px] border border-[#e1e9e3] bg-white p-4 shadow-[0_4px_15px_rgba(33,61,45,.045)]"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-full bg-[#dff3e6] text-[#087d47]"><ScanSearch className="h-4 w-4" /></span><h2 className="text-[15px] font-extrabold text-[#17231c]">Leaf Detection Result</h2></div><span className={`rounded-full px-3 py-1 text-[10px] font-bold ${result ? 'bg-[#edf8f0] text-[#16764d]' : 'bg-[#f4f7f4] text-[#8a968d]'}`}>{result ? '✓ Completed' : 'Not started'}</span></div><p className="mt-4 text-[11px] font-semibold text-[#718077]">Detected Class</p><div className="mt-1 flex items-center gap-3 rounded-[10px] border border-[#d9ebdd] bg-[#f3faf4] px-3 py-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#dff3e6] text-[#16764d]"><Leaf className="h-4 w-4" /></span><span className="min-w-0 flex-1 truncate text-[16px] font-extrabold capitalize text-[#16764d]">{result ? result.detectedClass || (detected ? 'tea leaf' : 'not a tea leaf') : 'No analysis yet'}</span><span className={`rounded-full border px-3 py-1 text-[10px] font-bold ${detected ? 'border-[#bfe2c9] text-[#16764d]' : 'border-[#f0b278] text-[#e77717]'}`}>{result ? detected ? 'Detected' : 'Review' : 'Waiting'}</span></div><div className="mt-3 grid grid-cols-3 gap-2"><Metric label="Confidence Score" value={`${(confidence * 100).toFixed(1)}%`} /><Metric label="Bounding Boxes" value={result?.boundingBoxes?.length || 0} /><Metric label="Model Status" value={result ? 'Completed' : 'Waiting'} /></div><div className="mt-3 flex gap-2 rounded-[10px] border border-[#dfece2] bg-[#f5faf6] p-3 text-[11px] leading-4 text-[#28754a]"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0" /><span>{result?.recommendation || 'Upload an image to verify whether the sample contains a tea leaf.'}</span></div><div className="mt-3 border-t border-[#edf1ed] pt-3"><p className="text-[11px] font-bold text-[#26372c]">Next step</p><p className="mt-1 text-[11px] leading-4 text-[#718077]">{detected ? 'Proceed to Tea Grade Classification or run disease detection on this sample.' : 'Upload a clearer tea leaf sample image and try again.'}</p></div></section>
}

function Metric({ label, value }) {
  return <div className="min-h-[64px] rounded-[9px] border border-[#e3ebe5] bg-white p-2.5"><p className="text-[10px] text-[#718077]">{label}</p><p className="mt-1 text-[13px] font-extrabold text-[#26372c]">{value}</p></div>
}

export default LeafDetectionResultPanel
